### ISSUE TITLE
Initial Index Screen Highlights Redundancies

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#629] opened 2015-03-24 20:29 UTC
To me, the landing page for the INDEX feels weird, all the articles look the same and seem to refer to the same thing.  

![screen shot 2015-03-24 at 4 26 18 pm](https://cloud.githubusercontent.com/assets/2352439/6812074/cd71c50a-d242-11e4-9c78-bcc1c7ca762f.png)

Is there any way we could randomize the initial list and make it appear more diverse?

**Comment by DinisCruz** [comment] 2015-03-26 22:23
The fix for https://github.com/TeamMentor/TM_4_0_Design/issues/629 will make this better

**Comment by roman87** [comment] 2015-03-27 12:31
I am also going to make this a dupe of https://github.com/TMContent/Lib_UNO/issues/21 since it is really all the same issue.

**Closed** 2015-03-27 12:35 UTC
Labels: Resolution: Duplicate
