### ISSUE TITLE
Password forgot HTML form Get Password button type must be 'submit' rather than 'button', the id of the button is also missing 

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#244] opened 2015-01-13 17:56 UTC
Password reset form won't be submitted because the button type is not 'submit', it was set to 'button'.

The id attribute is also missing, which is needed for browser automation tests.

![screen shot 2015-01-13 at 11 54 29 am](https://cloud.githubusercontent.com/assets/1732035/5725720/0f46a3a6-9b1b-11e4-8135-ad8d009180dc.png)

**Comment by DinisCruz** [comment] 2015-01-13 20:08
The root of the issue is at https://github.com/TeamMentor/TM_4_0_Design/blob/master/source/content/globals.jade#L41-L42 (note that that file will change locations, once @luchia fixes: https://github.com/TeamMentor/TM_4_0_Design/issues/243)

![image](https://cloud.githubusercontent.com/assets/656739/5728117/d592fc1e-9b5f-11e4-96e1-f5862240ecd3.png)

Note: as you can see on the screenshot (and code) the missing id has already been fixed (since it was breaking a couple tests)

**Comment by roman87** [comment] 2015-01-13 21:48
Do we still need unit tests for this or can we close this?

**Comment by michaelhidalgo** [comment] 2015-01-29 17:39
Addressed with this PR https://github.com/TeamMentor/TM_4_0_QA/pull/6

**Comment by michaelhidalgo** [comment] 2015-01-29 17:39
With Pull Request

**Comment by roman87** [comment] 2015-02-02 04:31
Pull request was merged. closing this.

**Closed by roman87** 2015-02-02 04:31 UTC
Labels: Action:Dev, P2, Type:Bug
