### ISSUE TITLE
Blinking Cursor after Initial Login - Questionable First User Experience

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#743] opened 2015-05-04 11:42 UTC
After logging in the user is left with what could almost be a "Blinking Cursor" screen, meaning that its not immediately obvious what they're supposed to do:

![screen shot 2015-05-04 at 7 36 27 am](https://cloud.githubusercontent.com/assets/2352439/7452810/52c8b74c-f230-11e4-81ba-b45ec836619f.png)

After going through all the nice graphics and stuff that lead to the login, one would expect a warmer welcome with some real UI to work with such as:

![screen shot 2015-05-04 at 7 38 18 am](https://cloud.githubusercontent.com/assets/2352439/7452846/ba54a786-f230-11e4-8247-cd5778256e63.png)

The only issue I see with this route is the fact that the starting content is very similar, almost duplicates of one another.  To handle this how about a nice TeamMentor Welcome splash perhaps with a brief description of what the user's looking at?

**Comment by roman87** [comment] 2015-05-04 16:46
@pjenney58  this is a duplicate of https://github.com/TeamMentor/TM_4_0_Design/issues/581 which we are going to work on this as part of Flare. Reasoning is that we cannot do this in Jade as there is no active content on the user browser. I am closing this as duplicate

**Closed by roman87** 2015-05-04 16:46 UTC
