### ISSUE TITLE
Change the "Access TEAM Mentor" button to "Login"

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#480] opened 2015-02-25 18:20 UTC

**Comment by luchia** [comment] 2015-02-25 23:02
Completed in the referenced commit.

![screen shot 2015-02-26 at 8 22 09 am](https://cloud.githubusercontent.com/assets/4547737/6382644/407994d2-bd9a-11e4-92d6-1d6508dc14a4.png)

**Comment by michaelhidalgo** [comment] 2015-02-26 03:38
@tekgirl77  would you like to add a test scenario for this fix? You can use this test as a reference (https://github.com/TeamMentor/TM_4_0_QA/blob/master/tests/regression-sprint-1.coffee#L114)  and actually add a new assertion for the Login button.

You can take a look at this other test too https://github.com/TeamMentor/TM_4_0_QA/blob/master/tests/regression-sprint-1.coffee#L251

**Comment by roman87** [comment] 2015-02-26 20:30
Looks good. Assinging to @tekgirl77 for Unit test

**Comment by DinisCruz** [comment] 2015-02-27 00:02
@tekgirl77 see also https://github.com/TeamMentor/TM_4_0_QA/blob/master/tests/jade/pages-anonymous.test.coffee#L139-L148

**Comment by tekgirl77** [comment] 2015-03-02 15:51
@roman87 @DinisCruz @michaelhidalgo I submitted a pull request for the login button unit tests, however the CI build failed due to other unit tests.

https://github.com/TeamMentor/TM_4_0_QA/pull/11

https://travis-ci.org/TeamMentor/TM_4_0_QA/builds/52359448

**Comment by DinisCruz** [comment] 2015-03-02 16:28
@tekgirl77 code is merged, I think we can close this now

**Closed** 2015-03-02 16:29 UTC
Labels: Action:UnitTest, Effort: Taster - 4h, P0, Sprint2, Type: Task
