### ISSUE TITLE
Show a message/page when an article is not found

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#410] opened 2015-02-09 11:01 UTC
This is the workflow:
1. I click on an existing article from the Top Articles list
2. The article is displayed.
3. Change the URL to point to a non-existing article

![screen shot 2015-02-09 at 4 44 28 am](https://cloud.githubusercontent.com/assets/1732035/6105356/e61bfaa6-b01b-11e4-9ad5-eaa19f7f3963.png)

4. Go back to http://localhost:1337/user/main.html
5. Note that the Top Article list is empty .

![screen shot 2015-02-09 at 4 59 10 am](https://cloud.githubusercontent.com/assets/1732035/6105007/6b28a626-b018-11e4-86e8-1d7345068845.png)

6. There is an error in the graph db

![screen shot 2015-02-09 at 5 00 26 am](https://cloud.githubusercontent.com/assets/1732035/6105033/9e5c694c-b018-11e4-91f3-14a9c9ea7051.png)

**Comment by roman87** [comment] 2015-02-09 20:36
Yep, very good catch!!

**Comment by luchia** [comment] 2015-02-09 21:08
I'll take it first.

**Comment by luchia** [comment] 2015-02-09 23:20
Now that I think about it, wouldn't it just show a 404 error?

**Comment by roman87** [comment] 2015-02-10 00:11
No, I think this should be an article not found error. Because it is really different than a general 404

**Comment by luchia** [comment] 2015-02-10 02:07
This has been fixed in the referenced commit.

![screen shot 2015-02-10 at 12 07 07 pm](https://cloud.githubusercontent.com/assets/4547737/6120115/5d4a0800-b11d-11e4-85df-ae8b43537536.png)

**Comment by DinisCruz** [comment] 2015-02-10 15:48
thx @luchia 

This is now wired and looks like this (running with live data)

![image](https://cloud.githubusercontent.com/assets/656739/6130285/24d49412-b13c-11e4-971c-028148ba5b90.png)

When the article exists, it looks like this:

![image](https://cloud.githubusercontent.com/assets/656739/6130308/38af022e-b13c-11e4-9709-f2ef9eba6132.png)


Here is the regression test

```coffee
  it 'article (bad id)', (done)->
    req =
      params: id: 123
      session: recent_Articles: [] , username : "abc"
    res =
      send : (data)->
        $ = cheerio.load(data)
        $('#content #oops').html().assert_Is 'Oops'
        $('#content p'    ).html().assert_Is 'That article doesn&apos;t exist.'
        done()

    using new Article_Controller(req,res), ->
      @.article()
```

The GraphDB is also correctly handling this case, and there is no error thrown

**Comment by DinisCruz** [comment] 2015-02-10 16:07
For reference here is the test that checks if the article content is showing up in the correct location (note that this runs from the TM_Design tests, so the GraphDB is being mocked)

```coffee
  it 'article (good id)', (done)->

    article_Id    = 'article-12345'
    article_Title = 'this is an title'
    article_Html  = 'html is here'

    req =
      params: id: article_Id
      session: recent_Articles: []

    res =
      send : (data)->
        $ = cheerio.load(data)
        $('#content #title').html().assert_Is article_Title
        $('#content #html' ).html().assert_Is article_Html
        done()

    graphService =
      node_Data: (id, callback)->
        if id is article_Id
          callback { title: article_Title }
      article_Html: (id, callback)->
        if id is article_Id
          callback article_Html

    using new Article_Controller(req,res), ->
      @.graphService = graphService
      @.article()
```

**Comment by michaelhidalgo** [comment] 2015-02-10 19:32
Yes this issue is fixed.

**Comment by roman87** [comment] 2015-02-11 21:36
Looks good. Closing

**Closed by roman87** 2015-02-11 21:36 UTC
Labels: Action:QA, Effort: Taster - 4h, P0, Sprint2, Type:Bug
