### ISSUE TITLE
When searching for ambiguous characthers, such as a'b"cdef, we should fail the search gracefully (WAS: Server error)

### ISSUE THREAD

**Issue by tecknicaltom** [TeamMentor/TM_4_0_Design#332] opened 2015-01-28 19:27 UTC
I did a search for my normal search term:
a'b"c<marquee>def

The application redirected me to https://beta.teammentor.net/graph/a%27b%22c%3Cmarquee%3Edef and gave me a server error:
Server Error in '/' Application.
Runtime Error
Description: An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.

**Comment by DinisCruz** [comment] 2015-01-28 19:30
you saw the image below right? 

![image](https://cloud.githubusercontent.com/assets/656739/5945114/10ecc36a-a724-11e4-9bf1-8e4012f56318.png)

which is interesting since that is running on a node back end

**Comment by DinisCruz** [comment] 2015-01-28 19:31
the local error we get is 

![image](https://cloud.githubusercontent.com/assets/656739/5945131/4229c6ee-a724-11e4-9b7f-4a8eca2f4ee0.png)

**Comment by tecknicaltom** [comment] 2015-01-28 19:31
yes, that's the error I saw (the white and yellow page)

**Comment by DinisCruz** [comment] 2015-01-28 19:33
cool, we'll look into it

And it is nice to see the searches your guys are trying

![image](https://cloud.githubusercontent.com/assets/656739/5945176/8b7bec28-a724-11e4-8942-bf0fc6c119e5.png)

**Comment by roman87** [comment] 2015-01-28 19:40
@DinisCruz  We are running behind a reverse proxy :) thats why you get the IIS error. Good thing to keep in mind when we make the search work.

**Comment by roman87** [comment] 2015-01-28 20:45
rewording this a bit for more actionable fix. and adding to be tracked with the search story

**Comment by DinisCruz** [comment] 2015-02-05 21:57
Here is the test that replicates the issue of the search not handing weird char (for reference the problem was an unhandled serialisation error)

```coffee
  it.only 'Issue 332 - When searching for ambiguous characters ... fail the search gracefully', (done)->
    check_Search_Payload = (payload, next)->
      page.open "/search?text=#{payload}", (html,$)->
        html.assert_Is '<html><head></head><body></body></html>'
        next()

    jade.login_As_User ()->
      check_Search_Payload '%00',->
        check_Search_Payload "a'b\"cdef'",->
          check_Search_Payload "a%27b%22c%3Cmarquee%3Edef",->
            check_Search_Payload '!@£$%^**()_+=-{}[]|":;\'\?><,./' ,->
              done()
```

**Comment by DinisCruz** [comment] 2015-02-05 21:59
Here is the regression test that shows the search is able to handle all sorts of weird chars

```coffee
  it.only 'Issue 332 - When searching for ambiguous characters ... fail the search gracefully', (done)->
    check_Search_Payload = (payload, next)->
      page.open "/search?text=#{payload}", (html,$)->
        $('form').attr().assert_Is { action: '/search', method: 'GET' }
        next()

    jade.login_As_User ()->
      check_Search_Payload '%00',->
        check_Search_Payload "a'b\"cdef'",->
          check_Search_Payload "a%27b%22c%3Cmarquee%3Edef",->
            check_Search_Payload '!@£$%^**()_+=-{}[]|":;\'\?><,./' ,->
              check_Search_Payload 'aaaa',->
                done()
```

**Comment by roman87** [comment] 2015-02-16 01:42
this is fixed. will follow up with Tom

**Comment by roman87** [comment] 2015-02-21 23:59
@tecknicaltom thanks again for this. This has been fixed in latest beta on https://beta.teammentor.net can you let me know if it works as expected. Thanks.

**Comment by tecknicaltom** [comment] 2015-02-23 21:16
looks fixed to me

**Comment by roman87** [comment] 2015-02-24 02:58
Cool.. Thank you... closing..

**Closed by roman87** 2015-02-24 02:58 UTC
Labels: Action:Close, Effort: Schooner - 1d, P0, Resolution: Tracking for CS, Sprint2, Storiable, Type: Question, Type:Bug
