### ISSUE TITLE
Forced to reauthenticate when attempting to read a Top Article

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#341] opened 2015-01-28 20:23 UTC
Step 0
Login to system

Step 1
Click on a top article:
![image](https://cloud.githubusercontent.com/assets/3578332/5946111/5e4c1ef8-a701-11e4-8ed1-3009fecd1299.png)

Step 2
Get auth dialog box
![image](https://cloud.githubusercontent.com/assets/3578332/5946132/734d8d3c-a701-11e4-85b3-3293ffdfd494.png)
Why is that happening?

Step 3
Close auth dialog box and go back and click on original top article link to view the article
[[ no -- this did not work.  I am still getting the auth dialog box when I try to read the article ]]

**Comment by DinisCruz** [comment] 2015-01-28 22:26
I believe you are hitting this issue https://github.com/TeamMentor/TM_4_0_Design/issues/194 which is basically caused by the fact that content is currently provided by this 3.5 version https://beta35.teammentor.net

**Comment by arvinddoraiswamy** [comment] 2015-01-29 18:05
Yes happens to me too :) Doesn't happen with 'Recently viewed articles' for whatever reason.

**Comment by roman87** [comment] 2015-02-01 23:27
Yep this is by design in this version. Next Beta should have a full article view page and this should not be an issue anymore. Tracking this here: https://github.com/TeamMentor/Master/issues/946

**Comment by DinisCruz** [comment] 2015-02-17 09:47
Latest beta http://beta.teammentor.net/ has the fixed version

**Comment by roman87** [comment] 2015-02-22 00:02
@BendixSpring and @arvinddoraiswamy thanks again for this. This has been fixed on the latest beta at https://beta.teammentor.net could you take a look and let me know if the fix works as expected.
Thanks.

**Comment by arvinddoraiswamy** [comment] 2015-02-23 05:33
Looks okay :)

**Comment by roman87** [comment] 2015-02-23 17:08
Cool. Closing this.

**Closed by roman87** 2015-02-23 17:08 UTC
Labels: Action:Close, P0, Resolution: Duplicate, Resolution: Tracking for CS, Sprint2, Storiable, Type: Feature Request, Type: Question
