### ISSUE TITLE
Collapsable Filter Sets?

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#745] opened 2015-05-04 11:59 UTC
The index screen has all of the filter items running down the right side and the user has to scroll down to see all that's available.  Would it be better to collapse them so the user could see all of the options available?

![screen shot 2015-05-04 at 7 56 16 am](https://cloud.githubusercontent.com/assets/2352439/7453065/62a065ae-f233-11e4-9a06-24da61212a85.png)

**Comment by roman87** [comment] 2015-05-04 16:56
This is a known issue and will be taken care of in Flare. This cannot be done in Jade as there is no active user side code. This is actually a duplicate of https://github.com/TeamMentor/TM_4_0_Design/issues/350 Closing this as dupe.

**Closed by roman87** 2015-05-04 16:56 UTC
