### ISSUE TITLE
Minor inconsistencies on flags icons show in articles

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#645] opened 2015-03-31 01:25 UTC
Looking at the the top 3 articles from index:

![image](https://cloud.githubusercontent.com/assets/656739/6910570/d09d191e-d74c-11e4-8f4d-2c7187e8a3f0.png)

http://localhost:1337/article/1a613dd54e6a/Perform-a-Security-Design-Inspection-for-Web-Applications

![image](https://cloud.githubusercontent.com/assets/656739/6910579/ea69b83e-d74c-11e4-9531-d5af522ce934.png)

http://localhost:1337/article/2142c74362bc/Perform-a-Security-Design-Review

![image](https://cloud.githubusercontent.com/assets/656739/6910587/fa35d7ac-d74c-11e4-94f9-b22349d93154.png)

http://localhost:1337/article/3f1ef62b8879/Security-Architecture-And-Design-Reviews-Are-Conducted

![image](https://cloud.githubusercontent.com/assets/656739/6910595/056397cc-d74d-11e4-8de1-3c5da7046c15.png)

**Comment by roman87** [comment] 2015-03-31 03:49
Interestingly, I can't reproduce this one

**Comment by luchia** [comment] 2015-03-31 06:57
So I was able to replicate this (in the browser, my icons aren't working) and I added a fix for it -

![screen shot 2015-03-31 at 4 55 49 pm](https://cloud.githubusercontent.com/assets/4547737/6913742/020ed72e-d7c7-11e4-852e-77223bc2abc3.png)
![screen shot 2015-03-31 at 4 56 41 pm](https://cloud.githubusercontent.com/assets/4547737/6913741/020c5080-d7c7-11e4-930c-b7a27da78111.png)

**Comment by DinisCruz** [comment] 2015-03-31 14:25
@luchia latest change is on master (and dev)

**Comment by roman87** [comment] 2015-03-31 21:36
Since I couldn't replicate it, Dinis is it working for you :)?

**Comment by roman87** [comment] 2015-04-20 05:05
@DinisCruz can you let me know if this is fixed and can be closed?

**Comment by roman87** [comment] 2015-05-05 17:57
TTL expired. Closing

**Closed by roman87** 2015-05-05 17:57 UTC
Labels: 1x effort: Taster, Action:Close, P0, Resolution: Fixed, Resolution: Tracking for CS, Sprint2, Type: Question, Type:Bug
