### ISSUE TITLE
[Q] Create poc page that shows all titles and titles encoding status

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#473] opened 2015-02-23 16:56 UTC
@michaelhidalgo this will help with #441 and the idea is to all @SergeTruth to quickly see which articles need encoding fixes

**Comment by michaelhidalgo** [comment] 2015-02-23 21:08
I did a quick search , there are 16 articles with encoding issues just in the article title. Here is the list.

I will do other searches to find encoding issues in the content.

956740f5-aa8c-42db-acad-066b94727426 | Don&#39;t Use Functions with Format String Parameters
26a68d55-95e2-4007-bfa6-d1eee30740de | Deallocation Functions Don&#39;t Throw Exceptions
2e732e9d-5677-40cc-8e33-c40ceacc056b | Destructors Don&#39;t Throw Exceptions
4a3f39a5-075b-46cc-bb52-67709c3647d9 | Error Messages Don&#39;t Reveal Sensitive Information
4f516756-cca0-4b52-a70f-cdc234fa246d | Logging Is Throttled So an Attacker Can&#39;t Overwhelm the Logs
500ae131-3373-4246-b6f5-b90128ab8e3c | User&#39;s Login Credentials Are Validated Before Use
bc62bfd6-a9e4-4dd3-b537-371ba32d5e34 | Unnecessary ASP.NET File Type Extensions Are Mapped to &quot;HttpForbiddenHandler&quot; in Machine.config.
df7fec21-2ac4-4810-a949-4e77faf8350a | Tracing Is Disabled &lt;trace Enable=&quot;false&quot;/&gt;
eae36b78-3a3a-4225-ac55-f2a165bc9ab4 | You Subscribed to Router Vendor&#39;s Security Notification Service
f53dd28f-744e-48a1-954f-3faa46618dd4 | The Certificate&#39;s Public Key Is Valid, All the Way to a Trusted Root Authority
fa97587e-ddd5-4a30-a7f4-81c2bf24c91c | Error Codes Are Used When Exceptions Aren&#39;t Possible
441b4138-1866-442f-8abb-6d05236d6fcb | Don&#39;t Throw Exceptions from Deallocation Functions
5c0c50cf-d3ed-462c-8ec7-2eb96cf23680 | Don&#39;t Reveal Sensitive Information in Error Messages
d0a056d3-aaed-4ccc-8b8c-e88da2df5e84 | Where Exceptions Aren&#39;t Possible, Return Error Codes
e7fd382a-c074-42e5-b02c-4d773627d23b | Don&#39;t Use User Input in Format Strings
fd06b089-88ea-43df-bc41-f111a1848116 | Don&#39;t Throw Exceptions from Destructors

**Comment by roman87** [comment] 2015-02-24 02:46
As discussed on the call, this should not be a POC page, but there should be a script that fixes as many encoding issue as possible, throwing exceptions for manual fix when need be. 
Given this, can we close this issue as dupe of #441, since we should track all related things there.

**Closed** 2015-03-16 11:31 UTC
Labels: Action:Close, Effort: Taster - 4h, Type:Quality
