### ISSUE TITLE
Wire up the Flare production pages

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#724] opened 2015-04-25 15:13 UTC
As seen here https://github.com/TeamMentor/TM_4_0_Design/issues/702#issuecomment-93606853

@luchia I'm opening this here since it's more focused than #702 (which I'm about to close)

**Comment by roman87** [comment] 2015-04-28 14:38
This is a dupe of #618 no :)?

**Comment by DinisCruz** [comment] 2015-04-30 19:49
Yeah we can use #618

**Comment by roman87** [comment] 2015-05-03 23:04
Closing as dupe of #618

**Closed by roman87** 2015-05-03 23:04 UTC
Labels: 3x effort: Schooner, Action:Dev, P0, Type: Task
