### ISSUE TITLE
Remediate performance prob caused by large amounts of empty sessions in _sessionData

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#834] opened 2015-05-25 23:35 UTC
After removing _sessionData it is now stable 

![image](https://cloud.githubusercontent.com/assets/656739/7803064/586c601c-033e-11e5-884d-dc526363d6f4.png)

But before it was peeking at 800 Mbs and with the _sessionData having 30Mb in size

My instinct is that this could be cause https://github.com/TeamMentor/TM_4_0_Design/blob/master/src/services/Session-Service.coffee#L30 (which could the one causing the IO block and data leak)

**Comment by roman87** [comment] 2015-05-26 03:34
I tried to run the offending _sessiondata file on local Windows VM (Windows 2012 64bit) and could not reproduce the problem. 
I am running commit 82094c3d58374af48f1eaedd5dc1f0724eb2b362
Author: Dinis Cruz <dinis.cruz@owasp.org>
which is the latest one from master

This is what is happening from the system perspective when request occurs to localhost:1337/teammentor

https://drive.google.com/open?id=0B38ToRPzK5DsUUFYYzhGRjl4Szg&authuser=0

**Comment by michaelhidalgo** [comment] 2015-05-26 03:47
Did you noticed performance issues in terms of cpu and memory ?

I will update the issue with screenshots from my Windows vm

El lunes, 25 de mayo de 2015, RomichG <notifications@github.com> escribió:

> I tried to run the offending _sessiondata file on local Windows VM
> (Windows 2012 64bit) and could not reproduce the problem.
> I am running commit 82094c3
> <https://github.com/TeamMentor/TM_4_0_Design/commit/82094c3d58374af48f1eaedd5dc1f0724eb2b362>
> Author: Dinis Cruz dinis.cruz@owasp.org
> <javascript:_e(%7B%7D,'cvml','dinis.cruz@owasp.org');>
> which is the latest one from master
>
> This is what is happening from the system perspective when request occurs
> to localhost:1337/teammentor
>
> https://drive.google.com/open?id=0B38ToRPzK5DsUUFYYzhGRjl4Szg&authuser=0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/834#issuecomment-105378905>
> .
>


-- 
Sent from Gmail Mobile

**Comment by DinisCruz** [comment] 2015-05-26 13:48
I'm replicating the issue (not as as but bit noticeable)

**Comment by DinisCruz** [comment] 2015-05-26 13:56
The prob was caused by the 'Amazon keep-alive' ping creation of a new session (which is stored, meaning that we had 190k session IDs)

Another reason why we need to move the session management into the GraphDB

**Comment by DinisCruz** [comment] 2015-05-26 14:11
Just pushed a fix for this, @michaelhidalgo can you also try it (it is on the **Issue_834_Clean_Sessions** branch )

**Comment by roman87** [comment] 2015-05-26 15:29
This shows that we need to re-think and re-evaluate our theories behind what we store. For example, 
- [ ] There is really no need to store the session of any non logged in user (which is what the keep-alives are)
- [ ] We also should clean up (and invalidate) the session of any logged in user after a configured amount of time
- [ ] Separate user data (i.e. articles visited, searches made etc) from session data. Session data should include authentication and session persistence information only. 
- [ ] And yes, store user data in noSQL DB.

**Comment by roman87** [comment] 2015-05-26 19:27
I send about 9000 requests in about 45 minutes and the _session data file did not grow. The system was performing ok during the time request were being sent. Average CPU usage was about 10-15% (2.5Ghz)

Let make this a patch to TM 4.0 and release it along with #836

**Comment by DinisCruz** [comment] 2015-05-27 21:54
this is now on release 4_0_1

**Comment by roman87** [comment] 2015-05-28 01:31
This is fixed in 4.0.1

**Closed by roman87** 2015-05-28 01:31 UTC
Labels: 1x effort: Taster, Action:QA, P0, Sprint2, Type:Bug
