### ISSUE TITLE
Server error in /

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/TM_4_0_Design#334] opened 2015-01-28 19:35 UTC
This is my search query:  I typed some really bad words here. 

Server Error in '/' Application.
The resource cannot be found.
Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly.

Requested URL: /graph/I typed some really bad words here.

**Comment by DinisCruz** [comment] 2015-01-28 19:37
btw, can you try to put a screenshot of what it looks like to you in these issues? If you are on OSX, you can copy and paste directly into one of these issues (in GitHub)

**Comment by roman87** [comment] 2015-01-28 20:54
Is the error message similar to this one https://github.com/TeamMentor/TM_4_0_Design/issues/332#issuecomment-71899151?

**Comment by roman87** [comment] 2015-02-01 18:14
I am going to close this as duplicate of #332. this issue will  also  be tracked there. https://github.com/TeamMentor/Master/issues/907

**Closed by roman87** 2015-02-01 18:14 UTC
