### ISSUE TITLE
Replace Navigate page with search result page showing all data

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#215] opened 2015-01-07 23:08 UTC
The items here 

![image](https://cloud.githubusercontent.com/assets/656739/5655091/e7bb2aa8-96c1-11e4-90ff-6c1a5be74b2f.png)

should be shown on the left here

![image](https://cloud.githubusercontent.com/assets/656739/5655103/fdcfbfb6-96c1-11e4-805e-5fbeacbf07a9.png)

**Comment by roman87** [comment] 2015-01-08 22:57
Closing as dupe of: #195

**Closed by roman87** 2015-01-08 22:57 UTC
Labels: Action:Dev, P0, Type: Task
