### ISSUE TITLE
Bug in articles search total 

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#742] opened 2015-05-03 21:12 UTC
Notice how the total is 113 but only 108 are shown

![image](https://cloud.githubusercontent.com/assets/656739/7446963/4a42bfae-f1e1-11e4-937f-d7c486a5174b.png)
....
![image](https://cloud.githubusercontent.com/assets/656739/7446968/5a6147f2-f1e1-11e4-97ee-32c1b60db33e.png)

This is caused by articles having the 'Scala' Tag but missing a title or description

@michaelhidalgo can you confirm this with your scripts?

**Comment by roman87** [comment] 2015-05-03 21:28
Hmm.. interesting, I am not getting the same thing.

![selection_204](https://cloud.githubusercontent.com/assets/1326120/7447020/9e448dd0-f1b9-11e4-8289-cde1820ecc1d.png)

**Comment by roman87** [comment] 2015-05-03 21:30
I think the bug is not with totaling, I think it has something to do with the issue we are discussing here:
https://github.com/TeamMentor/TM_4_0_Design/issues/704#issuecomment-97127200

**Comment by michaelhidalgo** [comment] 2015-05-03 23:54
I'm able to reproduce this issue, please see below image : 

![screen shot 2015-05-03 at 17 41 08](https://cloud.githubusercontent.com/assets/1732035/7447539/c0d092e2-f1bc-11e4-84a9-7d932cf059a2.png)

I ran my script and it seems like there should be 113 articles with Scala Play technology 

```csharp
return articles.ToList()
		     .Where(x=>x.Technology =="Scala Play")
		    .count()
```

However, If I get the articles assigned to a View, I get 108 

```
return articles.ToList()
				.Where(x=>x.Technology =="Scala Play" && x.View.notNull())
				.count();
```

**Comment by michaelhidalgo** [comment] 2015-05-04 12:16
It seems like Java has a similar issue :  There should be 312 articles but TM just display 250.

Unlike the previous case, according to the script there are 312 Java articles associated to a view. Do we have a limit on the number of articles to show?

![screen shot 2015-05-04 at 06 09 36](https://cloud.githubusercontent.com/assets/1732035/7453251/803deb9a-f224-11e4-90f7-020cf41d8e3d.png)

![screen shot 2015-05-04 at 06 09 18](https://cloud.githubusercontent.com/assets/1732035/7453250/803df13a-f224-11e4-8022-a88b2eaa9315.png)

**Comment by roman87** [comment] 2015-05-04 17:00
@michaelhidalgo To answer your second question, the behavior for Java search is correct. We Do have a limit of 250 articles to be shown at one time. You have to filter further down.
To answer your first question, try the exact match of "Scala Play" and you will see that you get the exact number of articles - 108. 
Btw, if you try searching for "java" lowercase, you will see 412 articles. I think this is because in the event of not exact match of the TAG, the search engine continues and does a plain text search. However if there is an exact match, it does not continue. 
I think we need to change it to make it case insensitive at least.

**Comment by michaelhidalgo** [comment] 2015-05-04 17:58
@roman87  you are right, searching for Scala Play it gives the accurate number of 108, however, by looking for Scala, it gives 113.

I ran the script and it seems like for Scala Play there are 113 articles. If you then get the Scala Lib articles that are in a view, you just get 108 : 

```coffee script
return articles.Where(x=>x.Technology=="Scala Play")
		       .Where(x=>x.View.notNull()).count()
```

**Comment by roman87** [comment] 2015-05-04 19:01
So are you saying we are actually searching through articles that are not in a view?

**Comment by DinisCruz** [comment] 2015-05-11 18:09
here is the root cause of the bug

![image](https://cloud.githubusercontent.com/assets/656739/7571596/8b633b1e-f810-11e4-8036-4b16cbc63307.png)

**Comment by DinisCruz** [comment] 2015-05-11 18:24
Fixed (with reference commit)

The case of different findings based on the exact match with a query (or tag) is a separate issue (we need to think about that one separately)

**Comment by DinisCruz** [comment] 2015-05-11 18:29
Note: you will need to delete this bad boy:

![image](https://cloud.githubusercontent.com/assets/656739/7572125/ec841fb4-f813-11e4-96b9-e0537ba822d8.png)

so that you don't get a cached result

![image](https://cloud.githubusercontent.com/assets/656739/7572131/f7961d30-f813-11e4-9710-cb372149ced0.png)

**Comment by roman87** [comment] 2015-05-12 05:22
@DinisCruz I still don't understand what was the bug and what was fixed. It also seems like we broke something that was working. https://github.com/TeamMentor/TM_4_0_Design/issues/704

**Comment by roman87** [comment] 2015-05-16 18:55
The rest of this is covered in #787 Closing this one.

**Closed by roman87** 2015-05-16 18:55 UTC
Labels: 1x effort: Taster, Action:Dev, P0, Sprint2, Type:Bug
