### ISSUE TITLE
Icons for articles

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#574] opened 2015-03-16 23:32 UTC
Create icons for articles that represent the different types of articles.

**Comment by luchia** [comment] 2015-03-17 04:19
I was thinking that we should use some colours outside of the specific TM colour scheme. I came up with three different colours that are quite bold but easily identifiable (see below) -

![colours](https://cloud.githubusercontent.com/assets/4547737/6681303/d70e1944-cc96-11e4-9c7d-359dde3d4261.jpg)

We still have the green, which I think may be an issue as our green is a pretty prominent part of the colour scheme. TM green is used for action items like links and buttons and now it's throwing in another green that doesn't follow that structure. Maybe we can try something else, I'd like to get opinions.

Regardless, this is what I was thinking in terms of positioning -

![screen shot 2015-03-17 at 10 52 31 am](https://cloud.githubusercontent.com/assets/4547737/6681323/191263e0-cc97-11e4-9eb5-a50cb8aa5b04.png)

This lines up with the other issue Brendon opened up about having article numbers. The right hand side of the article can be used for information (article type colours, article number etc).

One way we can tell our users how these colours apply is by creating a legend. Whether that's in the results panel -

![screen shot 2015-03-17 at 11 11 32 am](https://cloud.githubusercontent.com/assets/4547737/6681330/4bca465e-cc97-11e4-9c8e-ade203d1b3c7.png)
![screen shot 2015-03-17 at 11 11 29 am](https://cloud.githubusercontent.com/assets/4547737/6681335/55131b3c-cc97-11e4-9ec1-8a2ed273cfeb.png)

Or in the filters panel (although I think this is more likely to be missed) [where the type filters are]-

![screen shot 2015-03-17 at 10 52 31 am](https://cloud.githubusercontent.com/assets/4547737/6681339/6b1f11c4-cc97-11e4-9d99-b6a5c8d9d6d8.png)

This is a POC folder on the branch Issue_574 if you would like to see it for yourself.

**Comment by luchia** [comment] 2015-03-17 04:19
@roman87 @michaelhidalgo @DinisCruz @tekgirl77

**Comment by luchia** [comment] 2015-03-18 01:42
As per our meeting this morning, @roman87 's feedback was that we should have three icons that represent the types of article and the filters div would act as the legend. My only concern with this approach is that it might look odd that we only have icons for the for 3 out of however many filters. Regardless, I agree that the legend should not be in the results container anymore because we now have multiple filter selection which will be difficult to fit everything in.

I think we should put the icons on the filters div like this and the positioning of the icon in the same place as the above work -

![screen shot 2015-03-18 at 6 53 15 am](https://cloud.githubusercontent.com/assets/4547737/6700636/7306a18e-cd43-11e4-965f-48375297aae1.png)
![screen shot 2015-03-18 at 7 19 34 am](https://cloud.githubusercontent.com/assets/4547737/6700648/8441cb5e-cd43-11e4-95e0-5e625ad161a2.png)

Now the only thing about this is that I do really think this looks weird to have icons as one part of the filters div, but not for the others. I have a couple of solutions:

One is that we have icons for the other filter labels. This at least addresses the issue that there is missing icons and somewhat balances it out -

![screen shot 2015-03-18 at 8 12 44 am](https://cloud.githubusercontent.com/assets/4547737/6700836/978efc92-cd46-11e4-8b57-5d793acdb3ab.png)
![screen shot 2015-03-18 at 8 12 46 am](https://cloud.githubusercontent.com/assets/4547737/6700837/99808eda-cd46-11e4-83a2-90ded501dbda.png)

However, I still don't think this is quite right. It still seems odd and out of balance to not have icons for all filters. So, another idea is to have icons for each filter and I like this idea because there are two options as to how we do this.

The first is that every filter within a filter category has the same icon -

![screen shot 2015-03-18 at 8 22 17 am](https://cloud.githubusercontent.com/assets/4547737/6701044/ab5aec1a-cd49-11e4-8809-069ac028912d.png)

The second option is that every filter within a filter category has a different icon -

![screen shot 2015-03-18 at 8 28 32 am](https://cloud.githubusercontent.com/assets/4547737/6701049/c52b67b4-cd49-11e4-9567-ce079074c3b6.png)

It does seem a bit strange to have different icons for one filter category and not for the others, so I would like to use the last option. There are three things I'd like to point out:

* We currently use the icon font that comes with Foundation. This has served us really well and has a lot of variety in the icons we use *but* we don't have icons for the technologies in the set.
* This means that we would need to create our own icon font or icon set (png/jpg) and use those instead, which we have already done in Flare with the article de-duplicate.
* I would like to have everything the same so I am proposing that we move the technology icon set from the jpg/png file format and make it a typeface. This could add an extra HTTP request if it's a separate file unless I make an extension on the Foundation fontface file.

Let me know what you think.

**Comment by luchia** [comment] 2015-03-18 02:27
I referenced this issue on #568 because I think we should also consider following the position of what that issue has -

![screen shot 2015-03-18 at 9 16 41 am](https://cloud.githubusercontent.com/assets/4547737/6701493/fa42c180-cd4f-11e4-89f1-d2acfa943e0e.png)

And for reference, this is what it would look like together -

![screen shot 2015-03-18 at 9 19 30 am](https://cloud.githubusercontent.com/assets/4547737/6701539/cdea3a2c-cd50-11e4-9de9-9c94427add55.png)

**Comment by luchia** [comment] 2015-03-22 23:10
I just merged this to my branch. It has it's own POC page.

I tried different positioning for the icons in the filters div and one of the ones that you suggested Roman looks like this -

![screen shot 2015-03-22 at 7 05 45 pm](https://cloud.githubusercontent.com/assets/4547737/6769208/09822e84-d0c4-11e4-92a9-ed66966e72fa.png)

Or this -

![screen shot 2015-03-22 at 7 09 57 pm](https://cloud.githubusercontent.com/assets/4547737/6769210/1839c89c-d0c4-11e4-9ac5-0bbd16617e43.png)

These are okay, but I still think this one looks best -

![screen shot 2015-03-22 at 7 12 01 pm](https://cloud.githubusercontent.com/assets/4547737/6769211/202dfbe0-d0c4-11e4-9e29-f088c8bcd7ba.png)

In relation to the icons being on every filter, at the moment they have to be like that because I cannot select a specific filter to attach the icon to. Hopefully @Dinis can help me out with that one.

@Dinis, in the mixins file for this issue you can see the icons I need to attach commented out in both the articles and filters mixin. Let me know if there is anything I can do to help you with this one.

**Comment by roman87** [comment] 2015-03-23 14:45
So couple of things
1. Where is the POC page?
2. I am not sure we need Icons for "Phase". We need icons for Technologies, representing a technology and we need icons for article types. That is why I suggested putting the icons on the right of the Word and to the left of the number.  i.e. "C++" (Icon)        "number" 
3. You should pull the latest Lib_Uno library, as it has less technologies.

**Comment by DinisCruz** [comment] 2015-03-23 18:18
@luchia push it to me (and give it a P0) when you're done with your part

**Comment by luchia** [comment] 2015-03-23 22:28
@roman87 -

1. POC page is filters-icons-for-articles. This contains the icons for #568, #574 and #577 because I want to show what it all looks like together.
2. I can't control which icons are attached to filters, that's why it's on all of them. I tried what you suggested but I wasn't happy with it. I still think it looks best to the left of the filter.

To the right -

![screen shot 2015-03-22 at 7 05 45 pm](https://cloud.githubusercontent.com/assets/4547737/6769208/09822e84-d0c4-11e4-92a9-ed66966e72fa.png)
![screen shot 2015-03-22 at 7 09 57 pm](https://cloud.githubusercontent.com/assets/4547737/6769210/1839c89c-d0c4-11e4-9ac5-0bbd16617e43.png)

To the left -

![screen shot 2015-03-22 at 7 12 01 pm](https://cloud.githubusercontent.com/assets/4547737/6769211/202dfbe0-d0c4-11e4-9e29-f088c8bcd7ba.png)

3. I will pull the Lib_Uno repo this morning.

**Comment by DinisCruz** [comment] 2015-03-26 21:39
as seen by comment https://github.com/TeamMentor/TM_4_0_Design/issues/577#issuecomment-86727897 this has been added to the https://github.com/TeamMentor/TM_4_0_Design/tree/Issue_577_Article_Numbers branch and it looks quite cool:

![image](https://cloud.githubusercontent.com/assets/656739/6857654/5a0f4212-d400-11e4-94e5-5963ea36dafb.png)

Assigning to @luchia since there are a coupe css issues to fix

**Comment by roman87** [comment] 2015-03-30 19:32
So couple of things:
- [ ] Alignment is off on full article page. 
![selection_166](https://cloud.githubusercontent.com/assets/1326120/6904711/d0848130-d6f0-11e4-9ac7-628a5c32fc16.png)

- [ ] We need better icons for .NET, Scala, .NET 3.5 and for "ALL" Also note that I will change "All" to "Tech Independent". These articles is not for "All Technologies" but for all the general articles that do not apply to specific technoloyg

![selection_167](https://cloud.githubusercontent.com/assets/1326120/6904832/a4f06bd2-d6f1-11e4-806d-fefba0f5856d.png)

- [ ] I am not sure I understand (or like) the article for "Code Examples", perhaps "How-To" can also be different. 

![selection_168](https://cloud.githubusercontent.com/assets/1326120/6904867/e67f3308-d6f1-11e4-87f6-ca6e37833833.png)


- [ ] We need to make sure that these Icons are persistent on the main "Search" page.

**Comment by luchia** [comment] 2015-03-30 20:28
The alignment issue has been fixed on the article -
![screen shot 2015-03-31 at 6 14 03 am](https://cloud.githubusercontent.com/assets/4547737/6905864/4f88a4d4-d76e-11e4-8aad-0f4fede1e7f4.png)

We already have good icons for ASP.NET and Scala. I'm not sure why you can't see them (maybe @DinisCruz can help with that) -
![screen shot 2015-03-31 at 6 15 45 am](https://cloud.githubusercontent.com/assets/4547737/6905888/6dcda886-d76e-11e4-952f-dc9981ebb5d3.png)

As for the Tech independent icon, I updated another issue saying that we are starting to run out of matching icons for this project and suggested that we create our own typeface set so we don't have this issue anymore (#634). In the meantime, I had a look through Foundations list and pulled up a couple of other icons that may or may not be suitable, let me know what you think -

![screen shot 2015-03-31 at 6 17 42 am](https://cloud.githubusercontent.com/assets/4547737/6905921/99a85c76-d76e-11e4-9450-49d173c49b72.png)
Tech independent?

![screen shot 2015-03-31 at 6 17 57 am](https://cloud.githubusercontent.com/assets/4547737/6905922/99a89b1e-d76e-11e4-8576-fe8136958440.png)
Tech independent?

![screen shot 2015-03-31 at 6 19 53 am](https://cloud.githubusercontent.com/assets/4547737/6905923/99ac194c-d76e-11e4-9171-3fc2cb6e9d11.png)
Guideline?

Relating to making the icons available on the search page, would you like to show the user the type icon or the technology icon (or both)?

**Comment by roman87** [comment] 2015-03-30 21:36
Hmm, interesting. Have you tested with firefox?

Anything else for Tech Independent?  If not then lets go with the first choice.  And I agree we need our own typeface, but it won't happen soon enough :)

I like the guideline icon.

yes lets make them both there. This will be consistent across the app then.

**Comment by luchia** [comment] 2015-03-30 22:30
I did test in Firefox, so it's strange that you're having this issue -

![screen shot 2015-03-31 at 7 55 06 am](https://cloud.githubusercontent.com/assets/4547737/6907641/54716a28-d77b-11e4-91f5-e2194fb35d3e.png)

______

Not really anything else in the set that encompasses everything. I thought the asterisk was the most suitable given the limited options.

______

 I've added these as comments to the search page (main-app-view mixin in the search-mixins.jade file). @DinisCruz, can you please finish that part? When I add them, I get an error with this -

![screen shot 2015-03-31 at 8 28 36 am](https://cloud.githubusercontent.com/assets/4547737/6908401/21b89624-d780-11e4-9aba-6f34c47127a9.png)

**Comment by luchia** [comment] 2015-03-30 22:55
@roman87, what do you think about these?

![screen shot 2015-03-31 at 8 51 53 am](https://cloud.githubusercontent.com/assets/4547737/6908789/6e34bc78-d783-11e4-9a17-9e53c7a0b671.png)
![screen shot 2015-03-31 at 8 52 11 am](https://cloud.githubusercontent.com/assets/4547737/6908788/6e33cf7a-d783-11e4-9ab3-18c806076de7.png)
![screen shot 2015-03-31 at 8 53 03 am](https://cloud.githubusercontent.com/assets/4547737/6908790/6e34fa6c-d783-11e4-84cf-9655e985da66.png)

**Comment by luchia** [comment] 2015-03-30 23:01
Assigning to @roman87 to be closed.

**Comment by roman87** [comment] 2015-03-30 23:32
Now I have a "flag" for Scala, .NET and "All" :(
![selection_169](https://cloud.githubusercontent.com/assets/1326120/6909380/77e6cc04-d713-11e4-8021-ae32a139fd00.png)

**Comment by roman87** [comment] 2015-03-30 23:39
And looks like icons are not being picked up on the search result and index pages :(

![selection_171](https://cloud.githubusercontent.com/assets/1326120/6909461/6bd39f4a-d714-11e4-8f38-90a42b9f4126.png)

![selection_170](https://cloud.githubusercontent.com/assets/1326120/6909464/6f934de2-d714-11e4-8c74-e655bf48c024.png)

**Comment by roman87** [comment] 2015-03-30 23:45
And I did npm install just in case and have same results.

**Comment by DinisCruz** [comment] 2015-03-31 01:07
which server is this?

**Comment by DinisCruz** [comment] 2015-03-31 01:10
did you delete any files from .tmCache?
 
I think you need to at least delete the ./tmCache/data_cache folder and tm-uno (since there are new mappings)

**Comment by DinisCruz** [comment] 2015-03-31 01:21
I just pushed this https://github.com/TeamMentor/TM_4_0_Design/commit/55ecae3c2c10eed27bbc8e19cfc76b8aaf061b20 to fix the fact that the .NET and Scala icons were a flag (that was caused by a content change)

regarding the lack of flags in your articles, I think that is a cache issue (you don't need to re do the clone or html conversions, I think you just need to replace the search data)

**Comment by roman87** [comment] 2015-03-31 02:48
ok, so Icons look good now, and the flags were fixed by rebuilding the cache. Thanks @DinisCruz 
But I still have alignment issues, @luchia can you take a look

![team mentor 4 0 html version - iceweasel_173](https://cloud.githubusercontent.com/assets/1326120/6911446/d6f97302-d72e-11e4-81b5-c0ebfa55257d.png)

![selection_174](https://cloud.githubusercontent.com/assets/1326120/6911447/d9d33dc4-d72e-11e4-89dc-43a4e6271a05.png)

**Comment by DinisCruz** [comment] 2015-03-31 02:50
i can't reproduce those icons misalignment on that page. just on https://github.com/TeamMentor/TM_4_0_Design/issues/645

**Comment by roman87** [comment] 2015-03-31 03:46
maybe it has something to do with the browser size:
1182x780

**Comment by luchia** [comment] 2015-03-31 06:51
So I'm also having issues with my icons showing up -

![screen shot 2015-03-31 at 4 51 05 pm](https://cloud.githubusercontent.com/assets/4547737/6913669/25d043c4-d7c6-11e4-805c-b810d0fdc4d9.png)

I entered some random icons in via the browser and it seems to be working fine -

![screen shot 2015-03-31 at 4 50 43 pm](https://cloud.githubusercontent.com/assets/4547737/6913668/25ce3aa2-d7c6-11e4-8cb3-f7330056dc8a.png)

**Comment by roman87** [comment] 2015-04-04 23:00
Looks very good. Nice job all!

**Closed by roman87** 2015-04-04 23:00 UTC
Labels: Action:QA, Effort: Schooner - 1d, P0, Sprint2, Storiable, Type: Task
